# SPDX-FileCopyrightText: 2026 Stefan Götz <github.nooneelse@spamgourmet.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        args:
          - packages/initbot-core/src
          - packages/initbot-chat/src
          - packages/initbot-web/src
        pass_filenames: false
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
  - repo: local
    hooks:
      - id: check-python-versions
        name: check-python-versions
        entry: uv run check-python-versions
        language: system
        args:
          - packages/initbot-core
          - packages/initbot-chat
          - packages/initbot-web
        pass_filenames: false
        always_run: true
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: [initbot_core, initbot_chat, initbot_web, tests]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
