#!/bin/sh

# SPDX-FileCopyrightText: 2026 Stefan Götz <github.nooneelse@spamgourmet.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -ue

TOOLS_DIR="$(dirname "$0")"

UV_VERSION=$(curl -LsSf "https://api.github.com/repos/astral-sh/uv/releases/latest" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['tag_name'])")

fetch_sha256() {
    curl -LsSf \
        "https://github.com/astral-sh/uv/releases/download/${UV_VERSION}/$1.sha256" \
        | cut -d' ' -f1
}

UV_SHA256_DARWIN_ARM64=$(fetch_sha256 "uv-aarch64-apple-darwin.tar.gz")
UV_SHA256_DARWIN_X86_64=$(fetch_sha256 "uv-x86_64-apple-darwin.tar.gz")
UV_SHA256_LINUX_X86_64=$(fetch_sha256 "uv-x86_64-unknown-linux-gnu.tar.gz")
UV_SHA256_LINUX_AARCH64=$(fetch_sha256 "uv-aarch64-unknown-linux-gnu.tar.gz")

cat > "${TOOLS_DIR}/uv_version.sh" << EOF
#!/bin/sh

# SPDX-FileCopyrightText: 2026 Stefan Götz <github.nooneelse@spamgourmet.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by tools/update_uv_version.sh -- do not edit by hand
# shellcheck disable=SC2034  # variables are used by sourcing scripts
UV_VERSION="${UV_VERSION}"
UV_SHA256_DARWIN_ARM64="${UV_SHA256_DARWIN_ARM64}"  # pragma: allowlist secret
UV_SHA256_DARWIN_X86_64="${UV_SHA256_DARWIN_X86_64}"  # pragma: allowlist secret
UV_SHA256_LINUX_X86_64="${UV_SHA256_LINUX_X86_64}"  # pragma: allowlist secret
UV_SHA256_LINUX_AARCH64="${UV_SHA256_LINUX_AARCH64}"  # pragma: allowlist secret
EOF

echo "Updated ${TOOLS_DIR}/uv_version.sh to uv ${UV_VERSION}"
