#!/bin/sh

# SPDX-FileCopyrightText: 2026 Stefan Götz <github.nooneelse@spamgourmet.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by tools/update_uv_version.sh -- do not edit by hand
# shellcheck disable=SC2034  # variables are used by sourcing scripts
UV_VERSION="0.11.7"
UV_SHA256_DARWIN_ARM64="66e37d91f839e12481d7b932a1eccbfe732560f42c1cfb89faddfa2454534ba8"  # pragma: allowlist secret
UV_SHA256_DARWIN_X86_64="0a4bc8fcde4974ea3560be21772aeecab600a6f43fa6e58169f9fa7b3b71d302"  # pragma: allowlist secret
UV_SHA256_LINUX_X86_64="6681d691eb7f9c00ac6a3af54252f7ab29ae72f0c8f95bdc7f9d1401c23ea868"  # pragma: allowlist secret
UV_SHA256_LINUX_AARCH64="f2ee1cde9aabb4c6e43bd3f341dadaf42189a54e001e521346dc31547310e284"  # pragma: allowlist secret
