#!/bin/sh

# SPDX-FileCopyrightText: 2026 Stefan Götz <github.nooneelse@spamgourmet.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by tools/update_uv_version.sh -- do not edit by hand
# shellcheck disable=SC2034  # variables are used by sourcing scripts
UV_VERSION="0.11.13"
UV_SHA256_DARWIN_ARM64="196a58aa24da89144187670df7c407358028984537fbc2f8f2d8f7a2604980df"  # pragma: allowlist secret
UV_SHA256_DARWIN_X86_64="99aad3f4956f5b92efd83eca6d87bf03e10688899487ad541f904c9c25c61dc1"  # pragma: allowlist secret
UV_SHA256_LINUX_X86_64="f830ea3d38ae1492acf53cb7f2cd0f81d6ae22b42d2d7310a6c7d42c451e1a43"  # pragma: allowlist secret
UV_SHA256_LINUX_AARCH64="12366407dc1fdba5179b10bd69c11ebfc2eff25791366089c0b2f5701056efc5"  # pragma: allowlist secret
