name: CI/CD

on:
  push:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          version: "0.10.10"
          checksum: "3e1027f26ce8c7e4c32e2277a7fed2cb410f2f1f9320d3df97653d40e21f415b"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }}
      - name: black
        run: |
          .venv/bin/black --check initbot tests
      - name: flake8
        run: |
          .venv/bin/flake8 initbot tests
      - name: zizmor
        run: |
          .venv/bin/zizmor .github/workflows/
      - name: Pylint
        run: |
          .venv/bin/pylint initbot tests
      - name: mypy
        run: |
          .venv/bin/mypy -p initbot
      - name: test
        run: |
          api_key=x .venv/bin/coverage run -m --source=initbot pytest tests
          .venv/bin/coverage report
