name: CI/CD

on:
  push:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: Install dependencies
        run: poetry install
      - name: black
        run: |
          poetry run black --check initbot tests
      - name: Pylint
        run: |
          poetry run pylint initbot tests
      - name: mypy
        run: |
          poetry run mypy -p initbot
      - name: test
        run: |
          api_key=x poetry run coverage run -m --source=initbot pytest tests
          poetry run coverage report
